apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xappenvironments.apps.example.org
spec:
  group: apps.example.org
  names:
    kind: XAppEnvironment
    plural: xappenvironments
  claimNames:
    kind: AppEnvironment
    plural: appenvironments
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dbPassword:
                  type: string
                  description: "Password for PostgreSQL superuser/app users"
                enableGeoserver:
                  type: boolean
                  default: true
                  description: "Optionally deploy GeoServer alongside WordPress"
              required:
                - dbPassword
